### ISSUE TITLE
Why does parameter indexing work the way it does?

### ISSUE THREAD

**Issue by Chocohead** [CadixDev/Lorenz#28]
Perhaps this is a legacy from what was decided with #2, but I thought I'd ask anyway.

The indexing system Lorenz uses matches that one the JDT uses, indexing parameters by encountering order from 0. This contrasts with MCP, Enigma and Tiny V2 which all index parameters from 1 for non-static methods (to leave `this` as 0) and respect doubles and longs taking up two LVT slots (skipping the next index for them). Whilst the different might be quite subtle, it can make a bit of a mess:
```java
void methodA(int a, int b, int c);

static methodB(int a, long b, int c) {
}
```
Lorenz is an index out for `methodA` which is a little annoying but resolvable for MCP at least as it has a static method list for which any other method can have 1 taken off the parameter name index. With `methodB` Lorenz starts out consistently with the others, but then `c` has index 2 in Lorenz and 3 with the mapping formats. This is resolvable in Enigma and Tiny V2 as they both have the method descriptors so can take off the double/long gains appropriately.

If you combine both however you find a situation where neither mapping solution can work with Lorenz without additional outside information. MCP knows about static methods but not method descriptors, whilst Enigma and Tiny V2 know the opposite. The JDT however can know about both, as `IMethodBinding`s provide whether they are static and the types of any parameters.

Of course this is presuming following mapping formats was/is important, as opposed to just representing parameters as they're declared, given that it does put some onus on whatever is using Lorenz to also have to account for a method being static or parameters being doubles/longs. Guess the crux of the matter is whether this was an active consideration/decision for indexing to work the way it does or just a side effect of what is (to be fair) the most obvious way to do indexing from the surface.

**Comment by jamierocks** [comment]
I'll start with this: our support for parameter mappings needs improving.

As for your question, it really comes down to our definition of a paramater (something like `String name`) not necessarily being an entry in the LVT. We would also be unable to account for the `this` offset. Though, I would argue even if we could - it's an implementation detail.

I'd definitely be open to exploring the binary index of parameter mappings, if we can.

**Comment by jamierocks** [comment]
@Chocohead what ideas did you have in mind?

**Comment by jamierocks** [comment]
Changes were made in https://github.com/CadixDev/Lorenz/releases/tag/0.5.6 that essentially passes on the PITA.
