### ISSUE TITLE
Remapping fails on hidden fields

### ISSUE THREAD

**Issue by prplz** [CadixDev/Lorenz#29]
When remapping a field that shares its name with a field in the parent class, the parent's mapping is wrongly used instead. (Depends on the order that the classes are processed also). I believe I have narrowed it down to AbstractClassMappingImpl.complete

Example code:
```java
public class LorenzTest {

    static class Parent { int f; }
    static class Child extends Parent { int f; }

    private LorenzRemapper remapper;

    @Before
    public void setup() {
        MappingSet mappings = MappingSet.create();
        mappings.getOrCreateClassMapping("LorenzTest$Parent").createFieldMapping("f", "parentField");
        mappings.getOrCreateClassMapping("LorenzTest$Child").createFieldMapping("f", "childField");
        remapper = new LorenzRemapper(mappings, new ReflectionInheritanceProvider(getClass().getClassLoader()));
    }

    @Test
    public void testHiddenField() {
        assertEquals(remapper.mapFieldName("LorenzTest$Parent", "f", "I"), "parentField");
        assertEquals(remapper.mapFieldName("LorenzTest$Child", "f", "I"), "childField"); // fails
    }
    
    @Test
    public void testHiddenField2() {
        assertEquals(remapper.mapFieldName("LorenzTest$Child", "f", "I"), "childField");
        assertEquals(remapper.mapFieldName("LorenzTest$Parent", "f", "I"), "parentField");
    }
}
```

**Comment by jamierocks** [comment]
It will be `AbstractClassMappingImpl.complete` that is copying the mapping across - though I had thought it wouldn't override existing mappings.

I think that's all that's required here is just tweaking the aforementioned method to check if there is a previously existing mapping (on the plus side performance benefits too?).

cc @Minecrell as he designed the new inheritance system

**Comment by prplz** [comment]
This is what happens:
- On requesting the field mapping for the parent, an extra mapping gets added. Now it has `f->parentField untyped` and `f->parentField int`
- On completing the child class, the `f->parentField int` field mapping gets copied over, even though the child already has `f->childField untyped`
- Requesting the field mapping `f int` on the child returns `parentField`

**Comment by jamierocks** [comment]
Oh I see, its an issue of lacking descriptors.

The issue is effecively with `this.fields.putIfAbsent(mapping.getSignature(), mapping);`, as `FieldSignature`s are both names and descriptors.

**Comment by jamierocks** [comment]
Alright, I've given this some thought about how to proceed:

- Check for ambiguous cases (where a parent has a typed field of the correct name, but the class has a none-typed field).
- Mark our "synthetic" mappings (where one has been copied by a remapper), and don't copy them

I'm hesitant to act too swiftly here, as I'm concerned that any solution could have a knock-on effect and cause false-positive cases that should have been copied over - there are pros and cons of both above solutions (checking for ambiguous cases is probably the best bet though).

---

Though, in the mean time there is a solution - [field type providers](https://javadoc.io/doc/org.cadixdev/lorenz/latest/index.html) which can ensure that data is filled into the mappings during reading.
