### ISSUE TITLE
Flush isn't called on standard MappingFormats

### ISSUE THREAD

**Issue by ramidzkh** [CadixDev/Lorenz#37]
The only way to force the entire mapping to print is to use `TextMappingFormat#createWriter(Writer)` and flushing the writer yourself.
Effected formats: (All of them)
- `CSrgMappingFormat`
- `TSrgMappingFormat`
- `XSrgMappingFormat`
- `SrgMappingFormat`

## Reproducible test cases
```java
MappingSet mappings = MappingSet.create();
mappings.createTopLevelClassMapping("A", "B");
MappingFormats.SRG.createWriter(System.out).write(mappings);
MappingFormats.CSRG.createWriter(System.out).write(mappings);
MappingFormats.TSRG.createWriter(System.out).write(mappings);
MappingFormats.XSRG.createWriter(System.out).write(mappings);
```

**Comment by jamierocks** [comment]
Caused by https://github.com/CadixDev/Lorenz/commit/64b502c5cedb9faa7a2d118c76e7257ae674e727.

**Comment by jamierocks** [comment]
Fixed.
